import './icon.less'
// export { IconCustom } from './icon-custom'
export { IconBase } from './icon-base'
export { IconSvg } from './icon-svg'
export { createFromIconfont } from './create-from-iconfont'
export { createIcon } from './create-icon'

// export type { IconCustomProps, IconCustomRef } from './icon-custom'
export type { IconBaseProps } from './icon-base'
export type { IconSvgProps } from './icon-svg'
