name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run npm scripts
        run: |
          yarn install
          yarn lint
          yarn build
